### PR TITLE
Added getters for deny and allow lists

### PR DESCRIPTION
**Pull request by mercepluka**

### CODE REVIEW

**Comment by chefsale** [comment]
Why do we have both deny and allow lists?

**Comment by mercepluka** [comment]
> Why do we have both deny and allow lists?

After the deployment, all bridges are denied for all users. Allow lists are used to allow bridging with FT, NFT, and XSC. And deny list is used to explicitly deny accounts from using XSC for some contracts.

**Comment by chefsale** [comment]
😁

**Comment by ijerkovic** [comment]
> > Why do we have both deny and allow lists?
> 
> After the deployment, all bridges are denied for all users. Allow lists are used to allow bridging with FT, NFT, and XSC. And deny list is used to explicitly deny accounts from using XSC for some contracts.

We will emphasise this in the docs

**Review by ijerkovic — APPROVED** [review]

**Pull request merged**
